import test from 'node:test'; import assert from 'node:assert/strict'; import fs from 'node:fs/promises'; import os from 'node:os'; import path from 'node:path'; import {scan} from '../dist/index.js';
async function fixture(files){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'envlineage-'));for(const [p,c] of Object.entries(files)){const f=path.join(dir,p);await fs.mkdir(path.dirname(f),{recursive:true});await fs.writeFile(f,c)}return dir}
test('finds undocumented and unprovided required variable without leaking values',async()=>{const secret='super-secret-value-123';const dir=await fixture({'src/a.ts':'const x = process.env.API_KEY;','.env.example':`OTHER=${secret}\n`});const r=await scan(dir);assert.ok(r.findings.some(f=>f.id==='ENV001'&&f.variable==='API_KEY'));assert.ok(r.findings.some(f=>f.id==='ENV003'&&f.variable==='API_KEY'));assert.equal(JSON.stringify(r).includes(secret),false)});
test('static fallback is not required',async()=>{const dir=await fixture({'a.ts':'const port = process.env.PORT ?? "3000";','.env.example':'PORT=3000\n'});const r=await scan(dir);assert.equal(r.findings.some(f=>f.variable==='PORT'&&(f.id==='ENV001'||f.id==='ENV003')),false)});
test('ignores process.env text in comments and strings',async()=>{const dir=await fixture({'a.ts':'// process.env.NOPE\nconst x="process.env.NOPE2";\nconst y=process.env.YES;'});const r=await scan(dir);assert.equal(r.variables.some(v=>v.name==='NOPE'||v.name==='NOPE2'),false);assert.ok(r.variables.some(v=>v.name==='YES'))});
test('detects duplicate template declaration',async()=>{const dir=await fixture({'.env.example':'A=\nA=two\n'});const r=await scan(dir);assert.ok(r.findings.some(f=>f.id==='ENV005'&&f.variable==='A'))});
test('compose interpolation is not automatically a provider',async()=>{const dir=await fixture({'a.ts':'const x=process.env.TAG;','compose.yml':'services:\n  api:\n    image: app:${TAG:-latest}\n'});const r=await scan(dir);assert.ok(r.findings.some(f=>f.id==='ENV003'&&f.variable==='TAG'))});
test('compose environment provides variable',async()=>{const dir=await fixture({'a.ts':'const x=process.env.DB;','compose.yml':'services:\n  api:\n    environment:\n      DB: ${DB}\n'});const r=await scan(dir);assert.equal(r.findings.some(f=>f.id==='ENV003'&&f.variable==='DB'),false)});
test('github secrets reference is provider without value access',async()=>{const dir=await fixture({'a.ts':'const x=process.env.TOKEN;','.github/workflows/ci.yml':'jobs:\n  t:\n    runs-on: ubuntu-latest\n    env:\n      TOKEN: ${{ secrets.TOKEN }}\n'});const r=await scan(dir);assert.equal(r.findings.some(f=>f.id==='ENV003'&&f.variable==='TOKEN'),false);assert.ok(r.variables.find(v=>v.name==='TOKEN')?.providers.length)});
test('dynamic access remains unknown and does not invent variable',async()=>{const dir=await fixture({'a.ts':'const k="TOKEN"; const x=process.env[k];'});const r=await scan(dir);assert.ok(r.variables.some(v=>v.name==='<dynamic>'&&v.analysisState==='unknown'));assert.equal(r.findings.length,0)});
test('ENV004 requires evidence of relevance in multiple compose contexts',async()=>{const dir=await fixture({'a.ts':'const x=process.env.DB;','compose.yml':'services:\n  api:\n    environment:\n      DB: ${DB}\n  worker:\n    command: echo ${DB}\n'});const r=await scan(dir);assert.ok(r.findings.some(f=>f.id==='ENV004'&&f.variable==='DB'))});
test('docker ARG is not runtime provider while ENV is',async()=>{let dir=await fixture({'a.ts':'const x=process.env.KEY;','Dockerfile':'FROM node:22\nARG KEY\n'});let r=await scan(dir);assert.ok(r.findings.some(f=>f.id==='ENV003'&&f.variable==='KEY'));dir=await fixture({'a.ts':'const x=process.env.KEY;','Dockerfile':'FROM node:22\nENV KEY=value\n'});r=await scan(dir);assert.equal(r.findings.some(f=>f.id==='ENV003'&&f.variable==='KEY'),false)});
import {spawnSync} from 'node:child_process';
test('CLI exit policy and JSON output are CI-friendly',async()=>{const dir=await fixture({'a.ts':'const x=process.env.MISSING;'});let p=spawnSync(process.execPath,['dist/cli.js','scan',dir,'--format','json'],{cwd:process.cwd(),encoding:'utf8'});assert.equal(p.status,1);const body=JSON.parse(p.stdout);assert.equal(body.schemaVersion,'1');assert.equal(body.summary.errors,1);p=spawnSync(process.execPath,['dist/cli.js','scan',dir,'--severity','info','--no-color'],{cwd:process.cwd(),encoding:'utf8'});assert.equal(p.status,1);assert.equal(p.stdout.includes('\u001b['),false)});
test('invalid CLI option exits 2',()=>{const p=spawnSync(process.execPath,['dist/cli.js','scan','--wat'],{cwd:process.cwd(),encoding:'utf8'});assert.equal(p.status,2)});
