import fs from 'node:fs/promises'; import type {FileEntry} from './discovery.js'; import type {Diagnostic,Observation} from './types.js'; import {lineCol,loc} from './util.js';
function obs(variable:string,source:Observation['source'],relation:Observation['relation'],f:FileEntry,text:string,index:number,context:string,extra:Partial<Observation>={}):Observation{const p=lineCol(text,index);return {variable,source,relation,location:loc(f.rel,p.line,p.column),context,...extra}}
function stripCommentsAndStrings(input:string):string{let out='',i=0,state:'code'|'sq'|'dq'|'tpl'|'line'|'block'='code';while(i<input.length){const c=input[i]!,n=input[i+1]; if(state==='code'){if(c==='/'&&n==='/'){out+='  ';i+=2;state='line';continue}if(c==='/'&&n==='*'){out+='  ';i+=2;state='block';continue}if(c==="'"){out+=' ';i++;state='sq';continue}if(c==='"'){out+=' ';i++;state='dq';continue}if(c==='`'){out+=' ';i++;state='tpl';continue}out+=c;i++;continue} if(state==='line'){if(c==='\n'){out+='\n';state='code'}else out+=' ';i++;continue}if(state==='block'){if(c==='*'&&n==='/'){out+='  ';i+=2;state='code'}else{out+=c==='\n'?'\n':' ';i++}continue} if(c==='\\'){out+='  ';i+=2;continue} if((state==='sq'&&c==="'")||(state==='dq'&&c==='"')||(state==='tpl'&&c==='`')){out+=' ';i++;state='code';continue}out+=c==='\n'?'\n':' ';i++}return out}
export async function parseFile(f:FileEntry,diagnostics:Diagnostic[]):Promise<Observation[]>{let text='';try{text=await fs.readFile(f.abs,'utf8')}catch(e){diagnostics.push({level:'error',code:'IO_READ',message:`Cannot read ${f.rel}: ${String(e)}`});return[]}try{switch(f.kind){case'code':return parseCode(f,text);case'template':return parseTemplate(f,text);case'dockerfile':return parseDocker(f,text);case'compose':return parseCompose(f,text);case'github-actions':return parseActions(f,text)}}catch(e){diagnostics.push({level:'warning',code:'PARSE_PARTIAL',message:`Partial analysis for ${f.rel}: ${String(e)}`});return[]} }
function parseCode(f:FileEntry,text:string):Observation[]{const out:Observation[]=[]; const safe=stripCommentsAndStrings(text); const re=/\bprocess\s*\.\s*env\s*(?:\.\s*([A-Za-z_][A-Za-z0-9_]*)|\[\s*(['"])([A-Za-z_][A-Za-z0-9_]*)\2\s*\])/g; let m; while((m=re.exec(text))){const prefix=safe.slice(m.index,m.index+Math.min(m[0].length,12)); if(!/process\s*\.\s*env/.test(prefix))continue; const name=m[1]||m[3]; if(!name)continue; const tail=text.slice(re.lastIndex,re.lastIndex+80); const defaulted=/^\s*(?:\?\?|\|\|)\s*(?:['"`][^'"`]*['"`]|\d+|true|false)/.test(tail); out.push(obs(name,'code','consumer',f,text,m.index,`source:${f.rel}`,defaulted?{requirement:'defaulted',detail:'static fallback detected'}:{requirement:'required'})); if(defaulted)out.push(obs(name,'code','default',f,text,m.index,`source:${f.rel}`,{requirement:'defaulted'})) }
 const dyn=/\bprocess\s*\.\s*env\s*\[\s*(?!['"])([^\]]+)\]/g; while((m=dyn.exec(safe)))out.push(obs('<dynamic>','code','dynamic',f,text,m.index,`source:${f.rel}`,{requirement:'dynamic',detail:'computed process.env key'})); return out}
function parseTemplate(f:FileEntry,text:string):Observation[]{const out:Observation[]=[];const seen=new Map<string,number>();const lines=text.split(/\r?\n/);let off=0;for(let i=0;i<lines.length;i++){const raw=lines[i]!,trim=raw.trim();const m=/^(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=/.exec(trim);if(m){const name=m[1]!;out.push(obs(name,'template','documentation',f,text,off+raw.indexOf(name),`template:${f.rel}`));if(seen.has(name))out.push(obs(name,'template','documentation',f,text,off+raw.indexOf(name),`template:${f.rel}`,{detail:'duplicate declaration'}));seen.set(name,i+1)}off+=raw.length+1}return out}
function parseDocker(f:FileEntry,text:string):Observation[]{const out:Observation[]=[];let stage='global';let off=0;for(const raw of text.split(/\r?\n/)){const line=raw.trim();const fm=/^FROM\s+.+?(?:\s+AS\s+([\w.-]+))?$/i.exec(line);if(fm)stage=fm[1]||`stage@${off}`;let m=/^ARG\s+([A-Za-z_][A-Za-z0-9_]*)(?:=(.*))?$/i.exec(line);if(m)out.push(obs(m[1]!,'dockerfile','interpolator',f,text,off+raw.indexOf(m[1]!),`docker:${stage}`,{detail:'build ARG'}));m=/^ENV\s+([A-Za-z_][A-Za-z0-9_]*)\s*(?:=|\s)/i.exec(line);if(m)out.push(obs(m[1]!,'dockerfile','provider',f,text,off+raw.indexOf(m[1]!),`docker:${stage}`,{detail:'image ENV'}));off+=raw.length+1}return out}
function parseCompose(f:FileEntry,text:string):Observation[]{const out:Observation[]=[];const lines=text.split(/\r?\n/);let service='',section='',baseIndent=-1,off=0;for(const raw of lines){const indent=raw.search(/\S|$/),line=raw.trim();const sm=/^([A-Za-z0-9_.-]+):\s*$/.exec(line);if(indent===2&&sm&&service===''&&sm[1]!=='services'){} if(indent===2&&sm&& !['services','volumes','networks','configs','secrets'].includes(sm[1]!)){service=sm[1]!;section=''} if(service&&indent===4&&sm){section=sm[1]!;baseIndent=indent}
 const ctx=`compose:${service||'global'}`; if(service&&section==='environment'&&indent>baseIndent){let m=/^-\s*([A-Za-z_][A-Za-z0-9_]*)(?:\s*=\s*(.*))?$/.exec(line)||/^([A-Za-z_][A-Za-z0-9_]*)\s*:\s*(.*)$/.exec(line);if(m){const name=m[1]!;out.push(obs(name,'compose','provider',f,text,off+raw.indexOf(name),ctx,{detail:m[2]===undefined?'host passthrough':'service environment'}))}}
 const ire=/\$\{([A-Za-z_][A-Za-z0-9_]*)(?:(:?[-?+])(.*?))?\}/g;let im;while((im=ire.exec(raw))){const op=im[2]||'';const req=op.includes('?')?'required':op.includes('-')?'defaulted':'unknown';out.push(obs(im[1]!,'compose','interpolator',f,text,off+im.index,ctx,{requirement:req as any,detail:`compose interpolation ${op||'plain'}`}))}off+=raw.length+1}return out}
function parseActions(f:FileEntry,text:string):Observation[]{const out:Observation[]=[];const lines=text.split(/\r?\n/);let off=0;let envIndent:number|null=null;for(const raw of lines){const indent=raw.search(/\S|$/);const trimmed=raw.trim();if(/^env\s*:\s*$/.test(trimmed)){envIndent=indent}else if(trimmed&&!trimmed.startsWith('#')&&envIndent!==null&&indent<=envIndent){envIndent=null}if(envIndent!==null&&indent>envIndent){const env=/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*:\s*(.*)$/.exec(raw);if(env){out.push(obs(env[1]!,'github-actions','provider',f,text,off+raw.indexOf(env[1]!),`gha:${f.rel}`,{detail:'GitHub Actions env mapping'}))}}
 const re=/\$\{\{\s*(secrets|vars|env)\.([A-Za-z_][A-Za-z0-9_]*)\s*\}\}/g;let m;while((m=re.exec(raw)))out.push(obs(m[2]!,'github-actions',m[1]==='env'?'consumer':'provider',f,text,off+m.index,`gha:${f.rel}`,m[1]==='env'?{detail:`GitHub ${m[1]} reference`,requirement:'unknown'}:{detail:`GitHub ${m[1]} reference`}));off+=raw.length+1}return out}
