import type {Finding,Observation,VariableRecord} from './types.js'; import {fp} from './util.js';
const nameMap={ENV001:'REQUIRED_UNDOCUMENTED',ENV002:'DOCUMENTED_UNUSED',ENV003:'REQUIRED_UNPROVIDED',ENV004:'INCONSISTENT_COVERAGE',ENV005:'DUPLICATE_DECLARATION'} as const;
function mk(id:Finding['id'],v:string,severity:Finding['severity'],message:string,explanation:string,o:Observation,related:Observation[]=[],confidence:Finding['confidence']='high'):Finding{return{id,name:nameMap[id],variable:v,severity,message,explanation,location:o.location,related:related.map(x=>x.location),context:o.context,confidence,fingerprint:fp(id,v,o.context,o.location.path)}}
export function evaluate(name:string,observations:Observation[]):Finding[]{if(name==='<dynamic>')return[];const cs=observations.filter(o=>o.relation==='consumer');const docs=observations.filter(o=>o.relation==='documentation');const ps=observations.filter(o=>o.relation==='provider');const required=cs.filter(o=>o.requirement==='required');const out:Finding[]=[];
 if(required.length&&docs.length===0)out.push(mk('ENV001',name,'warning',`${name} is required by code but not documented.`,`A supported code consumer requires ${name}, but no supported env template documents it.`,required[0]!));
 if(docs.length&&!cs.length&&!observations.some(o=>o.source!=='template'&&(o.relation==='provider'||o.relation==='interpolator')))out.push(mk('ENV002',name,'info',`${name} is documented but has no supported consumer.`,`The variable appears in an env template, but EnvLineage found no supported code or configuration consumer.`,docs[0]!,[], 'medium'));
 if(required.length&&ps.length===0)out.push(mk('ENV003',name,'error',`${name} is required but no supported provider was found.`,`A required code consumer exists, but no Docker/Compose/GitHub Actions provider was found in the supported repository sources. External runtime injection may still exist.`,required[0]!,[], 'medium'));
 const dup=docs.filter(o=>o.detail==='duplicate declaration');if(dup.length)out.push(mk('ENV005',name,'warning',`${name} is declared more than once in an env template.`,`Duplicate declarations can hide which documented value is authoritative.`,dup[0]!,docs.filter(o=>o.location.path===dup[0]!.location.path)));
 const composeProviders=ps.filter(o=>o.source==='compose');const relevantCompose=observations.filter(o=>o.source==='compose'&&(o.relation==='provider'||o.relation==='interpolator'));const relevantContexts=new Set(relevantCompose.map(o=>o.context));const providerContexts=new Set(composeProviders.map(o=>o.context));if(required.length&&relevantContexts.size>1&&providerContexts.size>0&&providerContexts.size<relevantContexts.size)out.push(mk('ENV004',name,'warning',`${name} has inconsistent supported coverage.`,`The variable is relevant in multiple Compose service contexts but is provided in only a subset of them.`,required[0]!,relevantCompose,'medium'));
 return out}
export function buildRecords(observations:Observation[]):VariableRecord[]{const map=new Map<string,Observation[]>();for(const o of observations){const a=map.get(o.variable)||[];a.push(o);map.set(o.variable,a)}return [...map.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([name,os])=>{const findings=evaluate(name,os);return{name,consumers:os.filter(o=>o.relation==='consumer'),documentation:os.filter(o=>o.relation==='documentation'),providers:os.filter(o=>o.relation==='provider'),observations:os,findings,analysisState:name==='<dynamic>'?'unknown':os.some(o=>o.relation==='dynamic')?'partial':'resolved'}})}
